### ISSUE TITLE
Text parsed as number returning NaN

### ISSUE THREAD

**Issue by robindevouge** [maeligg/my-online-cookbook#16] opened 2021-06-09 16:39 UTC
Looks like the comma is parsed as a number, though it doesn't happen on other places where I also have some ingredients separated by commas without any numbers in it.

Here's the example:

![Capture d’écran 2021-06-09 à 18 37 07](https://user-images.githubusercontent.com/10241210/121394688-e23b4080-c951-11eb-982c-bfda737d91f1.png)
![Capture d’écran 2021-06-09 à 18 37 17](https://user-images.githubusercontent.com/10241210/121394690-e2d3d700-c951-11eb-9644-5b92eae458ec.png)

**Comment by maeligg** [comment] 2021-06-12 22:15
Hm weird I can't reproduce locally with the same string. I see that you fixed it on your site, what did you change ?

**Comment by maeligg** [comment] 2021-06-16 10:02
Closing for now, if you manage to reproduce let me know.

**Closed as completed by maeligg** 2021-06-16 10:02 UTC
